In [1]:
import numpy as np 
import pandas as pd 
 
# Data Visualisation 
import matplotlib.pyplot as plt  
import seaborn as sns 

import torch
import glob
from torchvision import transforms
import torch.nn as nn

In [2]:
housing = pd.DataFrame(pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Homework 1/hw1_data/Housing.csv")) 
housing.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [3]:
#Splitting the Data into Training and Testing Sets 
from sklearn.model_selection import train_test_split 
 
# We specify this so that the train and test data set always have the same rows, respec
np.random.seed(0) 
df_train, df_test = train_test_split(housing, train_size = 0.8, test_size = 0.2, random_state = 42)
df_train.shape

(436, 13)

In [4]:
num_vars = ['area', 'bedrooms', 'bathrooms', 'stories', 'parking','price'] 
df_Newtrain = df_train[num_vars] 
df_Newtest = df_test[num_vars] 
df_Newtrain.head()

     area  bedrooms  bathrooms  stories  parking    price
46   6000         3          2        4        1  7525000
93   7200         3          2        1        3  6300000
335  3816         2          1        1        2  3920000
412  2610         3          1        2        0  3430000
471  3750         3          1        2        0  3010000

In [5]:
import warnings 
warnings.filterwarnings('ignore') 
 
from sklearn.preprocessing import MinMaxScaler
  
scaler = MinMaxScaler() 
df_Newtrain[num_vars] = scaler.fit_transform(df_Newtrain[num_vars])
df_Newtest[num_vars] = scaler.fit_transform(df_Newtest[num_vars])
df_Newtest.head()

         area  bedrooms  bathrooms   stories   parking     price
316  0.365217  0.666667        0.5  0.333333  0.333333  0.200000
77   0.417391  0.333333        0.5  0.666667  0.000000  0.424242
360  0.203478  0.000000        0.0  0.000000  0.000000  0.169697
90   0.286957  0.333333        0.0  0.333333  0.000000  0.406061
493  0.196522  0.333333        0.0  0.000000  0.000000  0.090909

In [6]:
y_Newtrain = torch.tensor(df_Newtrain['price'].values)
y_Newtest = torch.tensor(df_Newtest['price'].values)
X_Newtrain = torch.tensor(df_Newtrain[['area', 'bedrooms', 'bathrooms', 'stories', 'parking']].values)
X_Newtest = torch.tensor(df_Newtest[['area', 'bedrooms', 'bathrooms', 'stories', 'parking']].values)

In [7]:
# A Python program to demonstrate working of OrderedDict
from collections import OrderedDict

seq_model1 = nn.Sequential(OrderedDict([
                                       ('hidden_layer', nn.Linear(5,8)),
                                       ('hidden_activation', nn.Tanh()),
                                       ('output_layer', nn.Linear(8, 1))
]))

In [8]:
import torch.optim as optim
optimizer = optim.SGD(seq_model1.parameters(), lr = 1e-2)

In [9]:
def training_loop1(n_epochs, optimizer, model, loss_fn, t_u_train, t_u_val, t_c_train, t_c_val):
  for epoch in range(1, n_epochs + 1):
    t_p_train = model(t_u_train.float())
    loss_train = loss_fn(t_p_train.float(), t_c_train.float())
    t_p_val = model(t_u_val.float())

    loss_val = loss_fn(t_p_val, t_c_val)

    optimizer.zero_grad()
    loss_train.backward()
    optimizer.step()

    correct = 0;
    total = 0;
  
    if epoch == 1 or epoch % 10 == 0:  # <3>
      print(f"Epoch {epoch}, Training loss {loss_train.item():.4f},"f" Validation loss {loss_val.item():.4f}")

In [10]:
training_loop1(n_epochs = 300,
              optimizer = optimizer,
              model = seq_model1,
              loss_fn = nn.MSELoss(),
              t_u_train = X_Newtrain,
              t_u_val = X_Newtest,
              t_c_train =  y_Newtrain,
              t_c_val = y_Newtest
              )

Epoch 1, Training loss 0.3542, Validation loss 0.3877
Epoch 10, Training loss 0.2053, Validation loss 0.2325
Epoch 20, Training loss 0.1193, Validation loss 0.1425
Epoch 30, Training loss 0.0764, Validation loss 0.0973
Epoch 40, Training loss 0.0551, Validation loss 0.0747
Epoch 50, Training loss 0.0447, Validation loss 0.0634
Epoch 60, Training loss 0.0396, Validation loss 0.0577
Epoch 70, Training loss 0.0371, Validation loss 0.0547
Epoch 80, Training loss 0.0358, Validation loss 0.0531
Epoch 90, Training loss 0.0351, Validation loss 0.0522
Epoch 100, Training loss 0.0347, Validation loss 0.0516
Epoch 110, Training loss 0.0345, Validation loss 0.0512
Epoch 120, Training loss 0.0343, Validation loss 0.0509
Epoch 130, Training loss 0.0342, Validation loss 0.0506
Epoch 140, Training loss 0.0341, Validation loss 0.0504
Epoch 150, Training loss 0.0339, Validation loss 0.0502
Epoch 160, Training loss 0.0338, Validation loss 0.0499
Epoch 170, Training loss 0.0337, Validation loss 0.0497
Epoch 180, Training loss 0.0336, Validation loss 0.0496
Epoch 190, Training loss 0.0335, Validation loss 0.0494
Epoch 200, Training loss 0.0334, Validation loss 0.0492
Epoch 210, Training loss 0.0333, Validation loss 0.0490
Epoch 220, Training loss 0.0333, Validation loss 0.0488
Epoch 230, Training loss 0.0332, Validation loss 0.0487
Epoch 240, Training loss 0.0331, Validation loss 0.0485
Epoch 250, Training loss 0.0330, Validation loss 0.0483
Epoch 260, Training loss 0.0329, Validation loss 0.0482
Epoch 270, Training loss 0.0328, Validation loss 0.0480
Epoch 280, Training loss 0.0327, Validation loss 0.0479
Epoch 290, Training loss 0.0327, Validation loss 0.0477
Epoch 300, Training loss 0.0326, Validation loss 0.0476

In [11]:
seq_model2 = nn.Sequential(
    nn.Linear(5,8),
    nn.Tanh(),
    nn.Linear(8, 4),
    nn.Tanh(),
    nn.Linear(4, 1)
)

In [ ]:
optimizer0 = optim.SGD(seq_model2.parameters(), lr = 1e-2)

In [12]:
training_loop1(n_epochs = 300,
              optimizer = optimizer0,
              model = seq_model2,
              loss_fn = nn.MSELoss(),
              t_u_train = X_Newtrain,
              t_u_val = X_Newtest,
              t_c_train =  y_Newtrain,
              t_c_val = y_Newtest
              )

Epoch 1, Training loss 0.0421, Validation loss 0.0514
Epoch 10, Training loss 0.0421, Validation loss 0.0514
Epoch 20, Training loss 0.0421, Validation loss 0.0514
Epoch 30, Training loss 0.0421, Validation loss 0.0514
Epoch 40, Training loss 0.0421, Validation loss 0.0514
Epoch 50, Training loss 0.0421, Validation loss 0.0514
Epoch 60, Training loss 0.0421, Validation loss 0.0514
Epoch 70, Training loss 0.0421, Validation loss 0.0514
Epoch 80, Training loss 0.0421, Validation loss 0.0514
Epoch 90, Training loss 0.0421, Validation loss 0.0514
Epoch 100, Training loss 0.0421, Validation loss 0.0514
Epoch 110, Training loss 0.0421, Validation loss 0.0514
Epoch 120, Training loss 0.0421, Validation loss 0.0514
Epoch 130, Training loss 0.0421, Validation loss 0.0514
Epoch 140, Training loss 0.0421, Validation loss 0.0514
Epoch 150, Training loss 0.0421, Validation loss 0.0514
Epoch 160, Training loss 0.0421, Validation loss 0.0514
Epoch 170, Training loss 0.0421, Validation loss 0.0514
Epoch 180, Training loss 0.0421, Validation loss 0.0514
Epoch 190, Training loss 0.0421, Validation loss 0.0514
Epoch 200, Training loss 0.0421, Validation loss 0.0514
Epoch 210, Training loss 0.0421, Validation loss 0.0514
Epoch 220, Training loss 0.0421, Validation loss 0.0514
Epoch 230, Training loss 0.0421, Validation loss 0.0514
Epoch 240, Training loss 0.0421, Validation loss 0.0514
Epoch 250, Training loss 0.0421, Validation loss 0.0514
Epoch 260, Training loss 0.0421, Validation loss 0.0514
Epoch 270, Training loss 0.0421, Validation loss 0.0514
Epoch 280, Training loss 0.0421, Validation loss 0.0514
Epoch 290, Training loss 0.0421, Validation loss 0.0514
Epoch 300, Training loss 0.0421, Validation loss 0.0514

PART 2

In [13]:
from torchvision import datasets
data_path = '/content/drive/MyDrive/Colab Notebooks/dlwpt-code-master/p1ch7'
cifar10 = datasets.CIFAR10(data_path, train = True, download = True)
cifar10_val = datasets.CIFAR10(data_path, train = False, download = True)

Files already downloaded and verified
Files already downloaded and verified

In [14]:
tensor_cifar10 = datasets.CIFAR10(data_path, train = True, download = False, transform = transforms.ToTensor())

In [15]:
seq_model3 = nn.Sequential(
    nn.Linear(3072, 512),
    nn.Tanh(),
    nn.Linear(512, 10),
    nn.LogSoftmax(dim = 1)
)
learning_rate = 1e-2

loss_fn = nn.NLLLoss()

n_epochs = 100

In [16]:
optimizer2 = optim.SGD(seq_model3.parameters(), lr = 1e-2)

In [17]:
train_loader = torch.utils.data.DataLoader(tensor_cifar10, batch_size = 64, shuffle = True)

In [18]:
for epoch in range(n_epochs):
  for imgs, labels in train_loader:
    batch_size = imgs.shape[0]
    out = seq_model3(imgs.view(batch_size, -1))
    loss = loss_fn(out, labels)

    optimizer2.zero_grad()
    loss.backward()
    optimizer2.step()

  print('Epoch: %d, Loss: %f' % (epoch, float(loss)))

Epoch: 0, Loss: 1.780646
Epoch: 1, Loss: 1.966249
Epoch: 2, Loss: 1.706369
Epoch: 3, Loss: 1.844546
Epoch: 4, Loss: 1.733257
Epoch: 5, Loss: 1.519671
Epoch: 6, Loss: 1.405102
Epoch: 7, Loss: 2.017780
Epoch: 8, Loss: 1.454800
Epoch: 9, Loss: 1.723328
Epoch: 10, Loss: 1.427096
Epoch: 11, Loss: 1.693599
Epoch: 12, Loss: 1.665089
Epoch: 13, Loss: 1.885216
Epoch: 14, Loss: 1.528966
Epoch: 15, Loss: 1.123073
Epoch: 16, Loss: 1.994227
Epoch: 17, Loss: 1.097452
Epoch: 18, Loss: 1.415273
Epoch: 19, Loss: 1.591368
Epoch: 20, Loss: 1.481892
Epoch: 21, Loss: 1.051662
Epoch: 22, Loss: 1.476918
Epoch: 23, Loss: 1.462769
Epoch: 24, Loss: 1.512672
Epoch: 25, Loss: 1.511660
Epoch: 26, Loss: 1.655207
Epoch: 27, Loss: 1.343202
Epoch: 28, Loss: 0.733506
Epoch: 29, Loss: 1.505677
Epoch: 30, Loss: 1.233494
Epoch: 31, Loss: 1.472013
Epoch: 32, Loss: 1.205979
Epoch: 33, Loss: 0.788418
Epoch: 34, Loss: 1.824008
Epoch: 35, Loss: 1.396895
Epoch: 36, Loss: 1.747947
Epoch: 37, Loss: 0.880318
Epoch: 38, Loss: 0.992062
Epoch: 39, Loss: 1.299464
Epoch: 40, Loss: 1.199800
Epoch: 41, Loss: 1.307444
Epoch: 42, Loss: 1.115796
Epoch: 43, Loss: 1.677802
Epoch: 44, Loss: 1.255614
Epoch: 45, Loss: 1.006148
Epoch: 46, Loss: 1.185544
Epoch: 47, Loss: 1.269521
Epoch: 48, Loss: 1.607094
Epoch: 49, Loss: 0.962084
Epoch: 50, Loss: 1.131406
Epoch: 51, Loss: 1.513047
Epoch: 52, Loss: 1.148331
Epoch: 53, Loss: 1.557142
Epoch: 54, Loss: 1.489722
Epoch: 55, Loss: 1.105927
Epoch: 56, Loss: 0.957686
Epoch: 57, Loss: 1.591956
Epoch: 58, Loss: 1.333236
Epoch: 59, Loss: 0.983044
Epoch: 60, Loss: 0.760363
Epoch: 61, Loss: 1.334234
Epoch: 62, Loss: 0.780826
Epoch: 63, Loss: 1.275846
Epoch: 64, Loss: 0.516015
Epoch: 65, Loss: 1.151465
Epoch: 66, Loss: 1.482359
Epoch: 67, Loss: 0.909761
Epoch: 68, Loss: 1.047314
Epoch: 69, Loss: 0.961022
Epoch: 70, Loss: 0.908656
Epoch: 71, Loss: 0.891544
Epoch: 72, Loss: 1.422024
Epoch: 73, Loss: 1.231328
Epoch: 74, Loss: 0.894611
Epoch: 75, Loss: 1.572878
Epoch: 76, Loss: 1.066124
Epoch: 77, Loss: 1.135807
Epoch: 78, Loss: 1.140530
Epoch: 79, Loss: 0.889043
Epoch: 80, Loss: 0.890253
Epoch: 81, Loss: 1.250829
Epoch: 82, Loss: 0.675708
Epoch: 83, Loss: 1.241663
Epoch: 84, Loss: 0.756725
Epoch: 85, Loss: 1.330976
Epoch: 86, Loss: 1.199534
Epoch: 87, Loss: 1.188276
Epoch: 88, Loss: 0.705326
Epoch: 89, Loss: 0.743525
Epoch: 90, Loss: 1.272587
Epoch: 91, Loss: 0.681805
Epoch: 92, Loss: 1.012478
Epoch: 93, Loss: 0.561289
Epoch: 94, Loss: 0.914848
Epoch: 95, Loss: 1.440466
Epoch: 96, Loss: 0.994987
Epoch: 97, Loss: 1.446439
Epoch: 98, Loss: 1.062311
Epoch: 99, Loss: 1.069359

In [19]:
val_cifar10 = datasets.CIFAR10(data_path, train = False, download = False, transform = transforms.ToTensor())
val_loader = torch.utils.data.DataLoader(val_cifar10, batch_size = 64, shuffle = False)

correct = 0
total = 0

with torch.no_grad():
  for imgs, labels in val_loader:
    batch_size = imgs.shape[0]
    outputs = seq_model3(imgs.view(batch_size, -1))
    _, predicted = torch.max(outputs, dim=1)
    total += labels.shape[0]
    correct += int((predicted == labels).sum())

  print("Accuracy: %f", correct/total)

Accuracy: %f 0.5036

In [20]:
seq_model4 = nn.Sequential(
    nn.Linear(3072, 1024),
    nn.Tanh(),
    nn.Linear(1024, 512),
    nn.Tanh(),
    nn.Linear(512, 128),
    nn.Tanh(),
    nn.Linear(128, 10),
    nn.LogSoftmax(dim = 1)
)

In [22]:
optimizer4 = optim.SGD(seq_model4.parameters(), lr = 1e-2)

In [23]:
for epoch in range(n_epochs):
  for imgs, labels in train_loader:
    batch_size = imgs.shape[0]
    out = seq_model4(imgs.view(batch_size, -1))
    loss = loss_fn(out, labels)

    optimizer4.zero_grad()
    loss.backward()
    optimizer4.step()

  print('Epoch: %d, Loss: %f' % (epoch, float(loss)))

Epoch: 0, Loss: 1.985415
Epoch: 1, Loss: 1.868036
Epoch: 2, Loss: 1.616011
Epoch: 3, Loss: 1.995185
Epoch: 4, Loss: 1.833654
Epoch: 5, Loss: 1.750344
Epoch: 6, Loss: 1.327803
Epoch: 7, Loss: 1.527654
Epoch: 8, Loss: 1.540205
Epoch: 9, Loss: 1.787890
Epoch: 10, Loss: 1.341311
Epoch: 11, Loss: 1.774140
Epoch: 12, Loss: 1.566347
Epoch: 13, Loss: 1.789437
Epoch: 14, Loss: 1.285825
Epoch: 15, Loss: 1.419855
Epoch: 16, Loss: 1.616258
Epoch: 17, Loss: 1.377061
Epoch: 18, Loss: 2.276571
Epoch: 19, Loss: 1.357914
Epoch: 20, Loss: 1.361613
Epoch: 21, Loss: 1.452897
Epoch: 22, Loss: 1.733461
Epoch: 23, Loss: 1.455681
Epoch: 24, Loss: 1.573330
Epoch: 25, Loss: 1.476217
Epoch: 26, Loss: 1.540040
Epoch: 27, Loss: 1.563037
Epoch: 28, Loss: 1.460449
Epoch: 29, Loss: 1.953887
Epoch: 30, Loss: 1.207303
Epoch: 31, Loss: 1.504387
Epoch: 32, Loss: 1.191701
Epoch: 33, Loss: 1.485681
Epoch: 34, Loss: 1.189649
Epoch: 35, Loss: 1.483974
Epoch: 36, Loss: 1.541728
Epoch: 37, Loss: 1.588422
Epoch: 38, Loss: 1.335679
Epoch: 39, Loss: 1.230058
Epoch: 40, Loss: 1.600372
Epoch: 41, Loss: 0.866793
Epoch: 42, Loss: 1.610712
Epoch: 43, Loss: 1.080686
Epoch: 44, Loss: 1.149693
Epoch: 45, Loss: 1.772126
Epoch: 46, Loss: 1.432854
Epoch: 47, Loss: 1.665642
Epoch: 48, Loss: 1.416750
Epoch: 49, Loss: 1.613449
Epoch: 50, Loss: 1.161142
Epoch: 51, Loss: 0.812792
Epoch: 52, Loss: 1.555219
Epoch: 53, Loss: 1.553267
Epoch: 54, Loss: 1.274785
Epoch: 55, Loss: 1.002375
Epoch: 56, Loss: 1.096829
Epoch: 57, Loss: 1.271928
Epoch: 58, Loss: 1.272315
Epoch: 59, Loss: 1.313394
Epoch: 60, Loss: 0.928735
Epoch: 61, Loss: 1.011059
Epoch: 62, Loss: 1.478589
Epoch: 63, Loss: 0.967177
Epoch: 64, Loss: 0.865672
Epoch: 65, Loss: 1.003129
Epoch: 66, Loss: 1.248697
Epoch: 67, Loss: 1.066291
Epoch: 68, Loss: 0.837311
Epoch: 69, Loss: 0.999134
Epoch: 70, Loss: 1.092679
Epoch: 71, Loss: 0.943883
Epoch: 72, Loss: 0.880572
Epoch: 73, Loss: 0.715099
Epoch: 74, Loss: 0.593858
Epoch: 75, Loss: 0.620928
Epoch: 76, Loss: 1.040688
Epoch: 77, Loss: 0.748879
Epoch: 78, Loss: 1.067027
Epoch: 79, Loss: 0.997044
Epoch: 80, Loss: 0.635466
Epoch: 81, Loss: 1.058005
Epoch: 82, Loss: 1.294229
Epoch: 83, Loss: 0.668420
Epoch: 84, Loss: 0.841996
Epoch: 85, Loss: 0.765210
Epoch: 86, Loss: 0.882252
Epoch: 87, Loss: 0.875679
Epoch: 88, Loss: 0.996347
Epoch: 89, Loss: 0.897064
Epoch: 90, Loss: 0.675710
Epoch: 91, Loss: 1.098550
Epoch: 92, Loss: 1.082346
Epoch: 93, Loss: 0.686642
Epoch: 94, Loss: 0.748939
Epoch: 95, Loss: 0.580267
Epoch: 96, Loss: 1.096355
Epoch: 97, Loss: 1.059743
Epoch: 98, Loss: 0.806323
Epoch: 99, Loss: 0.540948

In [24]:
correct1 = 0
total1 = 0

with torch.no_grad():
  for imgs, labels in val_loader:
    batch_size = imgs.shape[0]
    outputs = seq_model4(imgs.view(batch_size, -1))
    _, predicted = torch.max(outputs, dim=1)
    total1 += labels.shape[0]
    correct1 += int((predicted == labels).sum())

  print("Accuracy: %f", correct1/total1)

Accuracy: %f 0.5171